trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  # Caminho do projeto da sua API
  projectPath: '**/SistemaERPOnlineAPI.csproj'
  buildPlatform: 'AnyCPU' # Configurado sem espaços para ativar a pasta bin\ correta
  buildConfiguration: 'Release'

steps:
# 1. Garante a instalação do NuGet no ambiente do agente
- task: NuGetToolInstaller@1
  displayName: 'Garantir Instalador do NuGet'

# 2. Executa a restauração dos pacotes (como MySql.Data e Swashbuckle)
- powershell: |
    $csproj = Get-Item "$(projectPath)"
    $solutionDir = $csproj.Directory.Parent.FullName
    nuget restore "$($csproj.FullName)" -PackagesDirectory "$solutionDir\packages"
  displayName: 'Restaurar Pacotes NuGet via PowerShell'

# 3. Compila a Web API gerando uma pasta limpa com os arquivos finais
- task: VSBuild@1
  displayName: 'Compilar Web API (.NET Framework)'
  inputs:
    solution: '$(projectPath)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    # Extrai o site limpo (FileSystem) salvando na pasta temporária do agente
    msbuildArgs: '/p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl="$(build.artifactStagingDirectory)\SitePronto" /p:DeleteExistingFiles=True'
    clean: true

# 4. Compacta a pasta gerada em um arquivo unificado drop.zip
- task: ArchiveFiles@2
  displayName: 'Compactar Arquivos em drop.zip'
  inputs:
    rootFolderOrFile: '$(build.artifactStagingDirectory)\SitePronto'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(build.artifactStagingDirectory)\drop.zip'
    replaceExistingArchive: true

# 5. Publica o arquivo drop.zip para você poder baixá-lo na interface do Azure DevOps
- task: PublishBuildArtifacts@1
  displayName: 'Disponibilizar Download do drop.zip'
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)\drop.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
